In [1]:
import numpy as np
#1d array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [2]:
type(arr1)

numpy.ndarray

In [3]:
arr1.shape

(5,)

In [4]:
arr1.size

5

In [7]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [9]:
type(arr2)

numpy.ndarray

In [10]:
arr2.shape

(5,)

In [11]:
#2d array
arr2 = np.array([[1,2,3,4,5]])
arr2

array([[1, 2, 3, 4, 5]])

In [12]:
arr2.shape

(1, 5)

In [13]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
arr3.shape

(2, 5)

In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [22]:
arr1.dtype

dtype('int32')

In [23]:
arr1.ndim

1

In [24]:
arr2.ndim

2

In [25]:
arr3.ndim

2

In [26]:
arr1.itemsize

4

In [27]:
arr2.itemsize

4

In [28]:
arr3.itemsize

4

In [29]:
arr1

array([1, 2, 3, 4, 5])

In [30]:
arr2 =np.array([10,20,30,40,50])
arr2

array([10, 20, 30, 40, 50])

In [32]:
#element wise addition same index
arr1+arr2

array([11, 22, 33, 44, 55])

In [34]:
#ele wise subtraction
arr2-arr1

array([ 9, 18, 27, 36, 45])

In [35]:
#universal function
arr = np.array([1,2,3,4,5])
#square root
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [36]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [37]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [39]:
arr.size

5

In [41]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [44]:
#array slicing and indexing
arr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
arr[0][0]

1

In [47]:
arr[2][3]

12

In [48]:
arr[1][2:]

array([7, 8])

In [50]:
arr[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [51]:
arr[0,0]=100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [52]:
#statistical concept
# mean:0 and standdevaiton:1
data =np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev = np.std(data)

normalized_data  = (data-mean)/std_dev
normalized_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [53]:
#mean
np.mean(data)

3.0

In [54]:
np.median(data)

3.0

In [56]:
np.var(data)

2.0

In [57]:
np.std(data)

1.4142135623730951

In [63]:
#logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5 and data<=8)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()